# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/akhe/development/VSCP/vscp-tcpip-daemon;/home/akhe/development/VSCP/vscp-tcpip-daemon/cmake-includes")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libssl3 | libssl1.1")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "info@vscp.org")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SECTION "net")
set(CPACK_DEBIAN_PACKAGE_SUGGESTS "mosquitto")
set(CPACK_DEB_COMPONENT_INSTALL "OFF")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "vscp-tcpip-daemon built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/.git/;/build.*/;/\\.cache/;\\.swp$")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/home/akhe/development/VSCP/vscp-tcpip-daemon;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr")
set(CPACK_MODULE_PATH "/home/akhe/development/VSCP/vscp-tcpip-daemon/third-party/vscp/cmake/modules")
set(CPACK_NSIS_CONTACT "info@vscp.org")
set(CPACK_NSIS_DISPLAY_NAME "VSCP TCP/IP Daemon 26.09.0")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
set(CPACK_NSIS_HELP_LINK "https://docs.vscp.org/vscpd/")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME "VSCP TCP/IP Daemon")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "https://www.vscp.org")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/akhe/development/VSCP/vscp-tcpip-daemon/cmake-includes/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "info@vscp.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "The VSCP TCP/IP Daemon (vscpd) is the main control centre for the VSCP
(Very Simple Control Protocol) framework. It provides a TCP/IP interface
for connected clients and drivers.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "VSCP TCP/IP Daemon")
set(CPACK_PACKAGE_FILE_NAME "vscp-tcpip-daemon-26-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://www.vscp.org")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "vscp-tcpip-daemon 26")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "vscp-tcpip-daemon 26")
set(CPACK_PACKAGE_NAME "vscp-tcpip-daemon")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "The VSCP project")
set(CPACK_PACKAGE_VERSION "26")
set(CPACK_PACKAGE_VERSION_MAJOR "26")
set(CPACK_PACKAGE_VERSION_MINOR "09")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PRODUCTBUILD_DOMAINS "ON")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/akhe/development/VSCP/vscp-tcpip-daemon/LICENSE")
set(CPACK_RESOURCE_FILE_README "/home/akhe/development/VSCP/vscp-tcpip-daemon/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.31/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_PACKAGE_GROUP "Applications/System")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_REQUIRES "openssl-libs")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_RPM_PACKAGE_URL "https://www.vscp.org")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/.git/;/build.*/;/\\.cache/;\\.swp$")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/akhe/development/VSCP/vscp-tcpip-daemon;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/akhe/development/VSCP/vscp-tcpip-daemon/cmake-includes/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "vscp-tcpip-daemon-26-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_INSTALL_SCOPE "perMachine")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/akhe/development/VSCP/vscp-tcpip-daemon/cmake-includes/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
